export const GET_SLIDES_LOADING = 'GET_SLIDES_LOADING';
export const GET_SLIDES_SUCCESS = 'GET_SLIDES_SUCCESS';
export const GET_SLIDES_ERROR = 'GET_SLIDES_ERROR';

export const EDIT_SLIDE_START = 'EDIT_SLIDE_START';
export const EDIT_SLIDE_SUCCESS = 'EDIT_SLIDE_SUCCESS';
export const EDIT_SLIDE_ERROR = 'EDIT_SLIDE_ERROR';

export const DELETE_SLIDE_START = 'DELETE_SLIDE_START';
export const DELETE_SLIDE_SUCCESS = 'DELETE_SLIDE_SUCCESS';
export const DELETE_SLIDE_ERROR = 'DELETE_SLIDE_ERROR';

export const CREATE_SLIDE_START = 'CREATE_SLIDE_START';
export const CREATE_SLIDE_SUCCESS= 'CREATE_SLIDE_SUCCESS';
export const CREATE_SLIDE_ERROR= 'CREATE_SLIDE_ERROR';

export const GET_SLIDER_SETTINGS_LOADING = 'GET_SLIDER_SETTINGS_LOADING';
export const GET_SLIDER_SETTINGS_SUCCESS = 'GET_SLIDER_SETTINGS_SUCCESS';
export const GET_SLIDER_SETTINGS_ERROR = 'GET_SLIDER_SETTINGS_ERROR';

export const AUTH_LOADING = 'AUTH_LOADING';
export const AUTH_SUCCESS= 'AUTH_SUCCESS';
export const AUTH_ERROR= 'AUTH_ERROR';

export const GET_MEDIA_LOADING = 'GET_MEDIA_LOADING';
export const GET_MEDIA_SUCCESS = 'GET_MEDIA_SUCCESS';
export const GET_MEDIA_ERROR = 'GET_MEDIA_ERROR';

export const CONTROL_TOGGLE = 'CONTROL_TOGGLE';